var Observer = require('./observer');
var AutoRun = require('./autorun');
var Watcher = require('./watcher');
var expression = require('./expression');
var nextTick = require('./next-tick');
Observer.AutoRun = AutoRun;
Observer.Watcher = Watcher;
Observer.expression = expression;
Observer.nextTick = nextTick;
Observer.Observer = Observer;
module.exports = Observer;
//# sourceMappingURL=index.js.map