var Observer = require('./observer');
var AutoRun = require('./autorun');
var Watcher = require('./watcher');
var nextTick = require('./next-tick');
Observer.AutoRun = AutoRun;
Observer.Watcher = Watcher;
Observer.nextTick = nextTick;
module.exports = Observer;
//# sourceMappingURL=index.js.map